### DISCUSSION TITLE
シミュレーション環境の作成方法

### DISCUSSION THREAD

**Discussion by Hiroaki-Masuzawa** [IRSL-tut/CPS-lecture#3] [General]
2023/8/21-2023/8/25　実施したときのシミュレーション実施方法

1. URDFファイルの作成
    -  ```choreonoid_body2urdf AssembleRobot.body > AssembleRobot.urdf 2>/dev/null```
2. 制御用ファイルの作成
    - ```python3  $(dirname $(which choreonoid))/../lib/irsl_choreonoid_ros/python/generate_roscontroller_config.py --bodyfile AssembleRobot.body > roscontrol_config.yaml```
3. シミュレーション環境設定ファイルの作成
    - ```python3  $(dirname $(which choreonoid))/../lib/irsl_choreonoid_ros/python/generate_cnoid.py --bodyfile AssembleRobot.body --templatefile $(dirname $(which choreonoid))/../share/irsl_choreonoid_ros/config/choreonoid_ros_template.cnoid > sim.cnoid```
4. シミュレーション環境の立ち上げ
    - ```roslaunch irsl_choreonoid_ros sim_robot.launch  project_file:=/userdir/sim.cnoid model:=/userdir/AssembleRobot.urdf control_config:=/userdir/roscontrol_config.yaml robot_name:=AssembleRobot```

**Comment by Hiroaki-Masuzawa** [comment]
上記でうまくいかない場合
- `xxx.body`の４行目のロボット名がassemblerで設定したものと一致しているか確認し，違う場合は修正する．
- `xxx.body`内を`joint_name`検索し，自分が設定したjoint_nameがあるか確認する．
- `roscontrol.config.yaml`の先頭行がロボット名の場合，以下作業を行う
    - 先頭行を消す
    - ２行目のインデントを０にする（joint_controllerの前のスペースをすべて消す）
- joins以下の名前を自分で設定したjoint_nameに書き換える
- gains内に出てくるLINK_xを自分で設定したjoint_nameに書き換える
- `sim.cnoid`内の20行目と62行目にロボット名が記載されているはずだが，それが正しいかを確認する．

**Comment by Hiroaki-Masuzawa** [comment]
関節をROSを使って動かす例(非推奨)
```
import time
import rospy
from trajectory_msgs.msg import JointTrajectory, JointTrajectoryPoint 

rospy.init_node('publihser')
pub = rospy.Publisher('/AssembleRobot/joint_controler/command', JointTrajectory, queue_size=10)

wait_count = 0
while wait_count<10:
 if pub.get_num_connections()> 0:
     break
if pub.get_num_connections() == 0:
   print("Can't to connect")
   exit(1)
pub_msg = JointTrajectory()

# 自分のリンクを書く
pub_msg.joint_names.append('LINK_0')
pub_msg.joint_names.append('LINK_1')

for i in range(10):
    point = JointTrajectoryPoint()
    point.positions.append(i/10)
    point.positions.append(-i/10)
    point.time_from_start=rospy.Time.from_sec(i)
    pub_msg.points.append(point)
pub.publish(pub_msg)
```

**Comment by Hiroaki-Masuzawa** [comment]
RobotInterfaceを用いて使用する方法(推奨)
設定ファイル例 下で使う fullset_robot_robotinterface.yaml

- `$$your_robot_name$$` を使用するロボット名にする
- joint_namesを各自のロボットの関節名にする

```yaml
robot_model:
  name: $$your_robot_name$$
  url: 'file:///userdir/$$your_robot_name$$.body'

# mobile_base:
#   type: geometry_msgs/Twist
#   topic: /$$your_robot_name$$/cmd_vel
#   baselink: Root

joint_groups:
  -
    name: default
    topic: /$$your_robot_name$$/joint_controller/command
    # type: 'action' or 'command'
    type: command
    joint_names: ['JOINT0', 'JOINT1'] ## 各自のロボットの関節名

# devices:
#   -
#     topic: /robot/joint_states
#     class: JointState
#     name: joint_state
#   -
#     topic: /robot/TOFSensor/value
#     type: std_msgs/Float64
#     name: TOFsensor
#     rate: 10
#   -
#     topic: /robot/COLOR_Sensor1/value
#     type: std_msgs/ColorRGBA
#     name: COLORSensor
#     rate: 10
```

python コード例　新規でファイルを作成しターミナルでxxx.pyを名称を変更し，ターミナルで`python3 xxx.py`を実行する
```python
exec(open('/choreonoid_ws/install/share/irsl_choreonoid/sample/irsl_import.py').read())

ri = RobotInterface('fullset_robot_robotinterface.yaml')
ri.sendAngleVector(npa([0.3, 0.4]))　# 自分のロボットの関節数分npaのリストに数を入れる　(単位:rad)

```

**Reply by Hiroaki-Masuzawa** [reply]
```RobotInterface```でうまくいかないときは```RobotInterface.RobotInterface```にする

**Comment by Hiroaki-Masuzawa** [comment]
車輪ロボット用設定ファイル　ファイル: wheel.yaml
robot_nameと`WHEELx`については適宜書き換える
```
controller_name: wheel_controller
robot_name: robot
wheels:
- name: WHEEL0 
  rot_axis:
  - 1.0
  - 0.0
  - 0.0
  translation:
  - 0.055
  - 0.0
  - -0.0452
  wheel_radius: 0.024
- name: WHEEL3
  rot_axis:
  - 0.0
  - -1.0
  - 0.0
  translation:
  - 0.0
  - -0.055
  - -0.0452
  wheel_radius: 0.024
- name: WHEEL1
  rot_axis:
  - -1.0
  - 0.0
  - 0.0
  translation:
  - -0.055
  - 0.0
  - -0.0452
  wheel_radius: 0.024
- name: WHEEL2
  rot_axis:
  - 0.0
  - 1.0
  - 0.0
  translation:
  - 0.0
  - 0.055
  - -0.0452
  wheel_radius: 0.024
```

**Reply by Hiroaki-Masuzawa** [reply]
合わせてroscontrol_config.yamlを書き換える
```
joint_controller: # なければ消す
  type: "position_controllers/JointTrajectoryController"
  joints:
    - JOINT0
    - JOINT1
    - JOINT2
    - JOINT3
  gains:
    JOINT0:
      p: 100
      i: 10
      d: 1
    JOINT1:
      p: 100
      i: 10
      d: 1
    JOINT2:
      p: 100
      i: 10
      d: 1
    JOINT3:
      p: 100
      i: 10
      d: 1
wheel_controller:
  type: "position_controllers/JointTrajectoryController"
  joints:
    - WHEEL0
    - WHEEL1
    - WHEEL2
    - WHEEL3
  gains:
    WHEEL0:
      p: 100
      i: 10
      d: 1
    WHEEL1:
      p: 100
      i: 10
      d: 1
    WHEEL2:
      p: 100
      i: 10
      d: 1
    WHEEL3:
      p: 100
      i: 10
      d: 1
```

**Reply by Hiroaki-Masuzawa** [reply]
ターミナルで以下コマンドを実行しプログラム実行ファイルをコピーする
`cp /choreonoid_ws/install/share/irsl_choreonoid_ros/launch/sim_robot.launch .`
そして
 ` <group ns="$(arg robot_name)" >`と` </group>`の間に以下内容を書き加える
```
    <node name="wheelcontroller_node" pkg="irsl_choreonoid_ros" type="wheelcontroller.py" output="screen">
      <param name="wheelconfigfile" value="$(arg wheelconfigfile)" />
    </node>
 ```
また7行目付近の`<arg`とある付近に以下内容を追記する．
```
  <!-- wheel -->
  <arg name="wheelconfigfile" default="/userdir/wheel.yaml"/>
```

**Reply by Hiroaki-Masuzawa** [reply]
これ以降シミュレーション環境を実行するときにはirsl_choreonoid_rosを除いて実行する．

**Reply by Hiroaki-Masuzawa** [reply]
設定ファイル fullset_robot_robotinterface.yaml

 ` $$your_robot_name$$ `を使用するロボット名にする

```
robot_model:
  name: $$your_robot_name$$
  url: 'file:///userdir/$$your_robot_name$$.body'

mobile_base:
  type: geometry_msgs/Twist
  topic: /$$your_robot_name$$/cmd_vel
  baselink: Root

# joint_groups:
#   -
#     name: default
#     topic: /$$your_robot_name$$/joint_controller/command
#     # type: 'action' or 'command'
#     type: command
#     joint_names: ['JOINT0', 'JOINT1'] ## 各自のロボットの関節名

# devices:
#   -
#     topic: /robot/joint_states
#     class: JointState
#     name: joint_state
#   -
#     topic: /robot/TOFSensor/value
#     type: std_msgs/Float64
#     name: TOFsensor
#     rate: 10
#   -
#     topic: /robot/COLOR_Sensor1/value
#     type: std_msgs/ColorRGBA
#     name: COLORSensor
#     rate: 10
```
